"""Added test table11

Revision ID: 047ebbd8cb9c
Revises: 6f0dc367c61f
Create Date: 2018-07-26 19:38:48.496628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047ebbd8cb9c'
down_revision = '6f0dc367c61f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
