"""新增列,刪除平博id列1

Revision ID: 38ea0e8541f3
Revises: 857a30791b68
Create Date: 2018-07-31 16:55:11.219921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38ea0e8541f3'
down_revision = '857a30791b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dj_account', sa.Column('address', sa.String(length=512), nullable=True))
    op.add_column('dj_account', sa.Column('born', sa.String(length=255), nullable=True))
    op.add_column('dj_account', sa.Column('firstPayCoin', sa.Integer(), nullable=True))
    op.add_column('dj_account', sa.Column('firstPayTime', sa.Integer(), nullable=True))
    op.add_column('dj_account', sa.Column('sex', sa.String(length=32), nullable=True))
    op.alter_column('dj_account', 'realName',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('dj_agent_apply', 'introduction',
               existing_type=mysql.MEDIUMTEXT(),
               nullable=True)
    op.alter_column('dj_agent_apply', 'qq',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.add_column('dj_agent_commission', sa.Column('preBalance', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dj_agent_commission', 'preBalance')
    op.alter_column('dj_agent_apply', 'qq',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('dj_agent_apply', 'introduction',
               existing_type=mysql.MEDIUMTEXT(),
               nullable=False)
    op.alter_column('dj_account', 'realName',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('dj_account', 'sex')
    op.drop_column('dj_account', 'firstPayTime')
    op.drop_column('dj_account', 'firstPayCoin')
    op.drop_column('dj_account', 'born')
    op.drop_column('dj_account', 'address')
    # ### end Alembic commands ###
