"""Added test table22

Revision ID: 6be17b1c07f8
Revises: 047ebbd8cb9c
Create Date: 2018-07-26 19:40:45.620044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be17b1c07f8'
down_revision = '047ebbd8cb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
