"""Added test table

Revision ID: 6f0dc367c61f
Revises: 8bee5fadfc6a
Create Date: 2018-07-26 19:34:39.316287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f0dc367c61f'
down_revision = '8bee5fadfc6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('aa', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('aa'),
    mysql_charset='utf8mb4'
    )
    op.add_column('dj_account', sa.Column('realName', sa.String(length=255), nullable=False))
    op.add_column('dj_account', sa.Column('shabaCoin', sa.BigInteger(), nullable=True))
    op.add_column('dj_agent', sa.Column('code', sa.Integer(), nullable=False))
    op.add_column('dj_agent_commission', sa.Column('backWater', sa.Integer(), nullable=False))
    op.add_column('dj_agent_commission', sa.Column('balance', sa.Integer(), nullable=False))
    op.add_column('dj_agent_commission', sa.Column('bonus', sa.Integer(), nullable=False))
    op.add_column('dj_agent_commission', sa.Column('pingboRate', sa.Float(), nullable=False))
    op.add_column('dj_agent_commission', sa.Column('probetRate', sa.Float(), nullable=False))
    op.drop_column('dj_agent_commission', 'dividend')
    op.add_column('dj_pay_order', sa.Column('status', sa.SmallInteger(), nullable=False))
    op.add_column('dj_pinbo_wagers', sa.Column('settleDateFm', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_dj_pinbo_wagers_settleDateFm'), 'dj_pinbo_wagers', ['settleDateFm'], unique=False)
    op.create_index(op.f('ix_dj_pinbo_wagers_wagerDateFm'), 'dj_pinbo_wagers', ['wagerDateFm'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dj_pinbo_wagers_wagerDateFm'), table_name='dj_pinbo_wagers')
    op.drop_index(op.f('ix_dj_pinbo_wagers_settleDateFm'), table_name='dj_pinbo_wagers')
    op.drop_column('dj_pinbo_wagers', 'settleDateFm')
    op.drop_column('dj_pay_order', 'status')
    op.add_column('dj_agent_commission', sa.Column('dividend', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('dj_agent_commission', 'probetRate')
    op.drop_column('dj_agent_commission', 'pingboRate')
    op.drop_column('dj_agent_commission', 'bonus')
    op.drop_column('dj_agent_commission', 'balance')
    op.drop_column('dj_agent_commission', 'backWater')
    op.drop_column('dj_agent', 'code')
    op.drop_column('dj_account', 'shabaCoin')
    op.drop_column('dj_account', 'realName')
    op.drop_table('test_table')
    # ### end Alembic commands ###
