"""Added lastPBCRefush column in dj_account

Revision ID: 853a5ca016de
Revises: 38ea0e8541f3
Create Date: 2018-08-01 21:29:38.020870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853a5ca016de'
down_revision = '38ea0e8541f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dj_account', sa.Column('lastPBCRefreshTime', sa.Integer(), nullable=True,default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dj_account', 'lastPBCRefreshTime')
    # ### end Alembic commands ###
