"""Added test table44

Revision ID: 857a30791b68
Revises: f77f7265407c
Create Date: 2018-07-26 20:00:29.098632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857a30791b68'
down_revision = 'f77f7265407c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.batch_alter_table('dj_account', table_kwargs={'mysql_default_charset': 'utf8mb4'})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
