"""del test11

Revision ID: 8bee5fadfc6a
Revises: f5149bb47da8
Create Date: 2018-07-23 16:36:56.726904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bee5fadfc6a'
down_revision = 'f5149bb47da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
