"""init

Revision ID: a62a24a0e035
Revises: 1fe0e6b987d9
Create Date: 2018-07-23 16:15:22.734124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62a24a0e035'
down_revision = '1fe0e6b987d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dj_agent_apply',
    sa.Column('agentId', sa.String(length=64), nullable=False),
    sa.Column('applyTime', sa.Integer(), nullable=False),
    sa.Column('qq', sa.String(length=64), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('introduction', sa.Text(length=65536), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('agentId')
    )
    op.add_column('dj_admin_action', sa.Column('testAA', sa.Integer(), nullable=True))
    op.add_column('dj_agent_commission', sa.Column('platformCost', sa.Integer(), nullable=False))
    op.add_column('dj_agent_commission', sa.Column('winLoss', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dj_agent_commission', 'winLoss')
    op.drop_column('dj_agent_commission', 'platformCost')
    op.drop_column('dj_admin_action', 'testAA')
    op.drop_table('dj_agent_apply')
    # ### end Alembic commands ###
