"""新增列,刪除平博id列

Revision ID: 04594fbebbe7
Revises: c2fd1ed012f9
Create Date: 2018-07-31 14:39:02.579379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04594fbebbe7'
down_revision = 'c2fd1ed012f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dj_pingbobetbill', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dj_pingbobetbill', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
