"""新增列,刪除平博id列1

Revision ID: 2c96c4b757ae
Revises: 04594fbebbe7
Create Date: 2018-07-31 14:47:05.741914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c96c4b757ae'
down_revision = '04594fbebbe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
