"""新增列,刪除平博id列12

Revision ID: 307382d54074
Revises: 2c96c4b757ae
Create Date: 2018-07-31 14:51:35.766285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307382d54074'
down_revision = '2c96c4b757ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dj_pingbobetbill', sa.Column('id', sa.Integer(), nullable=True,primary_key=True,default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dj_pingbobetbill', 'id')
    # ### end Alembic commands ###
